apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: java-pure
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-flask
  targetCPUUtilizationPercentage: 70