apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: java-19-pure-apko-loom
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: java-19-pure-apko-loom
  targetCPUUtilizationPercentage: 70