apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: java-spring-gradle
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: java-spring-gradle
  targetCPUUtilizationPercentage: 70